export enum TiposCategoriaEnum {
  FILME = 'Filme',
  SERIE = 'Série',
  ANIMACAO = 'Animação',
  DOCUMENTARIO = 'Documentário',
}

export const tiposCategoriaColor = {
  [TiposCategoriaEnum.FILME]: 'primary',
  [TiposCategoriaEnum.SERIE]: 'secondary',
  [TiposCategoriaEnum.ANIMACAO]: 'success',
  [TiposCategoriaEnum.DOCUMENTARIO]: 'info',
};

export interface CatalogoItem {
  id: number;
  titulo: string;
  descricao: string;
  categoria: TiposCategoriaEnum;
  imagem: string;
  favorito?: boolean;
}

export function updateCatalogo(_: CatalogoItem[]) {
  catalogo = _;
}

// eslint-disable-next-line no-var
export var catalogo: CatalogoItem[] = [
  {
    id: 1,
    titulo: 'Planeta Azul',
    descricao: 'Natureza marinha',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
    favorito: true,
  },
  {
    id: 2,
    titulo: 'O Código da Vinci',
    descricao: 'Mistério e ação',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 3,
    titulo: 'Breaking Bad',
    descricao: 'Química criminal',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 4,
    titulo: 'Os Simpsons',
    descricao: 'Família amarela',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 5,
    titulo: 'Matrix',
    descricao: 'Realidade virtual',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 6,
    titulo: 'Cosmos',
    descricao: 'Universo explicado',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 7,
    titulo: 'Friends',
    descricao: 'Amizade em NY',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 8,
    titulo: 'O Rei Leão',
    descricao: 'Rei da selva',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 9,
    titulo: 'Chernobyl',
    descricao: 'Tragédia nuclear',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 10,
    titulo: 'Interestelar',
    descricao: 'Viagem no espaço',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 11,
    titulo: 'O Poderoso Chefão',
    descricao: 'Máfia e família',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 12,
    titulo: 'BoJack Horseman',
    descricao: 'Cavalo deprimido',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 13,
    titulo: 'Planeta Terra II',
    descricao: 'Natureza selvagem',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 14,
    titulo: 'La Casa de Papel',
    descricao: 'Roubo genial',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 15,
    titulo: 'O Irlandês',
    descricao: 'História de máfia',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 16,
    titulo: 'Rick and Morty',
    descricao: 'Viagem maluca',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 17,
    titulo: 'Making a Murderer',
    descricao: 'Crime real',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 18,
    titulo: 'Dark',
    descricao: 'Viagem no tempo',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 19,
    titulo: 'O Senhor dos Anéis',
    descricao: 'Fantasia épica',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 20,
    titulo: 'Avatar: O Caminho da Água',
    descricao: 'Mundo de Pandora',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 21,
    titulo: 'Mindhunter',
    descricao: 'Perfis criminais',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 22,
    titulo: 'Narcos',
    descricao: 'História de Pablo',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 23,
    titulo: "Chef's Table",
    descricao: 'Alta gastronomia',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 24,
    titulo: 'Shrek',
    descricao: 'Ogro carismático',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 25,
    titulo: 'Gladiador',
    descricao: 'Luta por Roma',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 26,
    titulo: 'Black Mirror',
    descricao: 'Futuro sombrio',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 27,
    titulo: 'Stranger Things',
    descricao: 'Coisas estranhas',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 28,
    titulo: 'O Menino e o Mundo',
    descricao: 'Desenho poético',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 29,
    titulo: 'Frozen',
    descricao: 'Poder do gelo',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 30,
    titulo: 'The Last Dance',
    descricao: 'História do Jordan',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 31,
    titulo: 'The Crown',
    descricao: 'Realeza britânica',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 32,
    titulo: 'Mulan',
    descricao: 'Coragem feminina',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 33,
    titulo: 'Sicario',
    descricao: 'Guerra contra drogas',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 34,
    titulo: 'Peaky Blinders',
    descricao: 'Máfia britânica',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 35,
    titulo: 'A Origem',
    descricao: 'Mente e sonhos',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 36,
    titulo: 'The Witcher',
    descricao: 'Mundo fantástico',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 37,
    titulo: 'Bohemian Rhapsody',
    descricao: 'História do Queen',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 38,
    titulo: 'O Jogo da Imitação',
    descricao: 'Segredos de guerra',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 39,
    titulo: 'The Mandalorian',
    descricao: 'Star Wars TV',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 40,
    titulo: 'Titanic',
    descricao: 'História do naufrágio',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 41,
    titulo: 'Toy Story',
    descricao: 'Brinquedos vivos',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 42,
    titulo: '1917',
    descricao: 'Guerra em plano',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 43,
    titulo: 'Planet Earth',
    descricao: 'Vida na Terra',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 44,
    titulo: 'House of Cards',
    descricao: 'Política suja',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 45,
    titulo: 'Zootopia',
    descricao: 'Cidade animal',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 46,
    titulo: 'Inception',
    descricao: 'Sonho e realidade',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 47,
    titulo: 'Dahmer',
    descricao: 'Serial killer',
    categoria: TiposCategoriaEnum.SERIE,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 48,
    titulo: 'Inside Job',
    descricao: 'Crise financeira',
    categoria: TiposCategoriaEnum.DOCUMENTARIO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 49,
    titulo: 'Moana',
    descricao: 'Aventura no mar',
    categoria: TiposCategoriaEnum.ANIMACAO,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 50,
    titulo: 'O Jogo da Imitação',
    descricao: 'Segredo de guerra',
    categoria: TiposCategoriaEnum.FILME,
    imagem: 'https://picsum.photos/300/300?random=1',
  },
];
